# Generated by Django 4.2.1 on 2023-06-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(upload_to='static/img/carousel_images'),
        ),
    ]
