# Generated by Django 4.2.1 on 2023-06-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_dash', '0003_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_images')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
